### ISSUE TITLE
html5lib is missing from requirements.txt

### ISSUE THREAD

**Issue by Elinvention** [angristan/isso-to-disqus#2]
I got this error: `bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: html5lib. Do you need to install a parser library?` and `pip install html5lib` fixed it. So I guess html5lib is missing from requirements.txt.

**Comment by angristan** [comment]
Thanks :)

**Comment by Elinvention** [comment]
Thank you for this software ;-)
